# Generated by Django 2.2.6 on 2019-12-26 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='other_party_role',
            field=models.CharField(choices=[('Site Owner', 'Site Owner'), ('Agency', 'Agency'), ('Creative', 'Creative Designer'), ('Publisher', 'Publisher')], default='AGENCY', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
