# Generated by Django 2.2.6 on 2019-12-26 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20191226_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractualpartyassociation',
            name='cp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='contracts.ContractualParty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractualpartyassociation',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contractualpartyassociation',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
