# Generated by Django 2.2.6 on 2019-12-27 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_auto_20191226_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContractualPartyAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(null=True)),
                ('association_type', models.CharField(choices=[('Administrator', 'Administrator'), ('Collaborator', 'Collaborator')], max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='contractualparty',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContractualPartyAssociation',
        ),
        migrations.AddField(
            model_name='usercontractualpartyassociation',
            name='cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.ContractualParty'),
        ),
        migrations.AddField(
            model_name='usercontractualpartyassociation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
